### ISSUE TITLE
Remove Invoke-WebRequest Internet Explorer dependancy

### ISSUE THREAD

**Issue by unplanned-restart** [TsekNet/WinTZ#1]
Add -UseBasicParsing to Invoke-WebRequest to remove IE dependency. Attached txt copies of modified cmdlets.

[ConvertTo-WindowsTimeZone.txt](https://github.com/TsekNet/WinTZ/files/7080707/ConvertTo-WindowsTimeZone.txt)
[Get-IANATimeZone.txt](https://github.com/TsekNet/WinTZ/files/7080708/Get-IANATimeZone.txt)

**Comment by TsekNet** [comment]
Thanks @rdodd66 - this is fixed. New version pushed to the PowerShell Gallery as well!
