### ISSUE TITLE
Script needs to be relooked up 

### ISSUE THREAD

**Issue by theg00d1** [TsekNet/WinTZ#2]
PS C:\WINDOWS\system32> Set-WindowsTimeZone -force
Setting Windows Time Zone to
Failed to set timezone: Cannot bind argument to parameter 'Name' because it is null.
At C:\Users\ankya\OneDrive\downloads\Documents\WindowsPowerShell\Modules\WinTZ\0.2.2\Public\Set-WindowsTimeZone.ps1:45
char:7
+       throw "Failed to set timezone: $_"
+       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Failed to set t...use it is null.:String) [], RuntimeException
    + FullyQualifiedErrorId : Failed to set timezone: Cannot bind argument to parameter 'Name' because it is null.

**Comment by TsekNet** [comment]
Hey, it seems your `$windows_time_zone` variable is not set for some reason, coming from [here](https://github.com/TsekNet/WinTZ/blob/e75642fde1a9eeb3ddfd272ad55488858f5e69f7/src/WinTZ/Public/Set-WindowsTimeZone.ps1#L42C27-L42C44). I'm not able to reproduce your issue. What's the result of running  `ConvertTo-WindowsTimeZone` locally on your system?

**Comment by theg00d1** [comment]
![image](https://github.com/user-attachments/assets/0b1284a2-1242-404f-a8bb-f4f4747eb7ca)

Check out & let me know i am running on Windows 11 pro Version	10.0.22631 Build 22631

**Comment by TsekNet** [comment]
Interesting. The issue seems to be that https://raw.githubusercontent.com/unicode-org/cldr/master/common/supplemental/windowsZones.xml lists `Asia/Kolkata` as `Asia/Calcutta`. Does the module work when you do `Set-WindowsTimeZone -IANATimeZone Asia/Calcutta`?

**Comment by theg00d1** [comment]
yes it does, i believe lets blame it on  Indian Government to keep on changing the names :P 

![image](https://github.com/user-attachments/assets/2c657db0-92ce-4a53-b359-b09a8cbb76ba)

Any recommended solution ?

**Comment by TsekNet** [comment]
It seems Kolkata is the most recent one (coming from ip-api.com), so my recommendation would be to open a PR to update unicode's [windowszones.xml](https://github.com/unicode-org/cldr/blob/main/common/supplemental/windowsZones.xml) explaining that the name was updated over 20 years ago and change their references to [Calcutta](https://github.com/unicode-org/cldr/blob/110107efc42ddd343303be99f4ad9f9b3b7529db/common/supplemental/windowsZones.xml#L557) to be the newer Kolkata to match ip-api.com
